version: '3.8'
services:
  service-1:
    container_name: "service-1"
    image: enahsedrof/service-1
    build: ./service_1
    ports:
    - target: 5000
      published: 5000
    environment:
    - DATABASE_URI=${DATABASE_URI}
    deploy:
            replicas: 3
        
  service-2:
    container_name: "service-2"
    image: enahsedrof/service-2
    build: ./service_2
    ports:
      - '5001:5001'
    deploy:
        replicas: 3

  service-3:
    container_name: "service-3"
    image: enahsedrof/service-3
    build: ./service_3
    ports:
      - '5002:5002'
    deploy:
        replicas: 3  

  service-4:
    container_name: "service-4"
    image: enahsedrof/service-4
    build: ./service_4
    ports:
      - '5003:5003'
    deploy:
        replicas: 3
        